server:
  port: 8096

spring:

  match:
    symbols:
      BTC_USDT:
        coinScale: 8        # BTC 精度
        baseCoinScale: 2    # USDT 精度
      ETH_USDT:
        coinScale: 8
        baseCoinScale: 2
      LTC_USDT:
        coinScale: 8
        baseCoinScale: 2
      BTC_ETH:
        coinScale: 8
        baseCoinScale: 8


  application:
    name: cex-matching-engine
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.23.51:3306/cex-admin?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  profiles:
    active: dev

  config:
    import: optional:nacos:${nacos.server}:8848?namespace=public&group=DEFAULT_GROUP&extension=yaml

  cloud:
    nacos:
      config:
        server-addr: ${nacos.server}:8848
        namespace: public
        group: DEFAULT_GROUP
        username: ${nacos.username}
        password: ${nacos.password}
        refresh-enabled: true
      discovery:
        server-addr: ${nacos.server}:8848
        namespace: public
        group: DEFAULT_GROUP
        username: ${nacos.username}
        password: ${nacos.password}

  disruptor:
    enabled: true
    ring-buffer-size: 1048576
    multi-producer: false
    wait-strategy: yielding
    fail-fast: true

rocketmq:
  name-server: 43.138.23.51:9876

  consumer:
    group: matching-engine-consumer-group
    topic: ORDER_TOPIC
    tag: "*"
# ============================================================
#
# ============================================================
logging:
  level:
    org.apache.rocketmq.client: INFO
    org.apache.rocketmq.remoting: INFO