
server:
  port: 8094

spring:
  application:
    name: cex-exchange-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.138.23.51:3306/cex-admin?useSSL=false&serverTimezone=UTC
    username: root
    password: root

  profiles:
    active: dev

  config:
    import: optional:nacos:${nacos.server}:8848?namespace=public&group=DEFAULT_GROUP&extension=yaml

  cloud:
    nacos:
      config:
        server-addr: ${nacos.server}:8848
        namespace: public
        group: DEFAULT_GROUP
        username: ${nacos.username}
        password: ${nacos.password}
        refresh-enabled: true
      discovery:
        server-addr: ${nacos.server}:8848
        namespace: public
        group: DEFAULT_GROUP
        username: ${nacos.username}
        password: ${nacos.password}


rocketmq:
  name-server: 43.138.23.51:9876

  producer:
    group: matching-engine-producer-group
    topic: ORDER_TOPIC

#        access-key: rocketAdmin         # 对应 plain_acl.yml 的账户
#        secret-key: 12345678
#      consumer:
#        group: matching-engine-consumer-group
#        access-key: rocketAdmin
#        secret-key: 12345678
# ============================================================
#
# ============================================================
logging:
  level:
    root: info
    com.cex: debug